// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto": { "en": "Auto", "de": "Auto", "ru": "Автоматически", "pt": "Auto", "nl": "Auto", "fr": "Auto", "it": "Auto", "es": "Auto" },
    "Manual": { "en": "Manual", "de": "Manual", "ru": "Вручную", "pt": "Manual", "nl": "Met de hand", "fr": "Manuel", "it": "Manuale", "es": "Manual" },
    "My select": { "en": "My select", "de": "Mein Auswahl", "ru": "Выбор", "pt": "Meu selecionado", "nl": "Mijn select", "fr": "Mon choix", "it": "La mia selezione", "es": "Mi seleccion" },
    "on save adapter restarts with new config immediately": { "en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato" },
    "template adapter settings": { "en": "template adapter settings", "de": "Beispiel", "ru": "Пример", "pt": "configurações do adaptador de modelo", "nl": "sjabloon-adapterinstellingen", "fr": "paramètres de l'adaptateur de modèle", "it": "impostazioni dell'adattatore del modello", "es": "configuración del adaptador de plantilla" },
    "test1": { "en": "Test 1", "de": "Test 1", "ru": "Тест 1", "pt": "Teste 1", "nl": "Test 1", "fr": "Test 1", "it": "Test 1", "es": "Prueba 1" },
    "test2": { "en": "Test 2", "de": "Test 2", "ru": "Тест 2", "pt": "Teste 2", "nl": "Test 2", "fr": "Test 2", "it": "Test 2", "es": "Prueba 2" },

    "pve login user": {
        "en": "pve login user",
        "de": "pve Login-Benutzer",
        "ru": "Пользователь",
        "pt": "usuário de login pve",
        "nl": "pve login gebruiker",
        "fr": "pve utilisateur de connexion",
        "it": "utente login pve",
        "es": "pve usuario de inicio de sesión",
        "pl": "użytkownik logowania pve"
    },
    "pve login password": {
        "en": "pve login password",
        "de": "Pve Login Passwort",
        "ru": "Пароль входа в систему",
        "pt": "senha de login",
        "nl": "pve login wachtwoord",
        "fr": "pve login mot de passe",
        "it": "password di accesso pve",
        "es": "pve contraseña de inicio de sesión",
        "pl": "hasło do logowania pve"
    },
    "password": {
        "en": "password",
        "de": "Passwort",
        "ru": "пароль",
        "pt": "senha",
        "nl": "wachtwoord",
        "fr": "mot de passe",
        "it": "parola d'ordine",
        "es": "contraseña",
        "pl": "hasło"
    },
    "ip adress": {
        "en": "ip adress",
        "de": "IP Adresse",
        "ru": "IP адрес",
        "pt": "Endereço de IP",
        "nl": "IP adres",
        "fr": "adresse IP",
        "it": "indirizzo IP",
        "es": "dirección IP",
        "pl": "adres IP"
    }
};